yarnPath: .yarn/releases/yarn-3.6.2.cjs
nodeLinker: node-modules
npmScopes:
  'deltix':
    npmAlwaysAuth: true
    npmAuthIdent: ${NPM_USER}:${NEXUS_PASS}
    npmRegistryServer: 'https://nexus.deltixhub.com/repository/epm-rtc-npm/'
