logging:
  level:
    root: info
    com.epam.deltix.quantgrid: debug

web:
  storage:
    local:
      resultsFolder: ${RESULTS_FOLDER:tmp/.cache}
      inputsFolder: ${INPUTS_FOLDER:tmp/inputs}
    dial:
      enabled: ${WEB_STORAGE_DIAL_INPUT_ENABLED:false}
      baseUrl: ${WEB_STORAGE_DIAL_BASE_URL}
      appKey: ${WEB_STORAGE_DIAL_APP_KEY}
  heartbeatPeriodMillis: 5000

spring:
  security:
    enabled: ${SECURITY_ENABLED:false}